version: '3.9'
services:
  backend:
    build:
      context: ./api
      target: production
    image: pm_backend
    container_name: 'pm_backend'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - './api/.env'
    ports:
      - "3001:3001"
    healthcheck:
      test: "nc -z localhost 3001"
  db:
    image: postgres:15.1-alpine3.16
    container_name: 'pm_db'
    env_file:
      - './.env'
    ports:
      - "3002:5432"
    volumes:
      - pm-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q | echo $? || exit 1
volumes:
  pm-data:
